# Generated by Django 5.2.14 on 2026-05-21 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuilderRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=200)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('recommendation_ready', 'Recommendation Ready'), ('plan_generated', 'Plan Generated'), ('cta_clicked', 'CTA Clicked')], default='in_progress', max_length=30)),
                ('current_stage', models.IntegerField(default=1)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('team_size', models.CharField(blank=True, max_length=100)),
                ('training_goal', models.TextField(blank=True)),
                ('focus_type', models.CharField(blank=True, max_length=50)),
                ('budget_tier', models.CharField(blank=True, max_length=30)),
                ('timeline', models.CharField(blank=True, max_length=200)),
                ('entry_point', models.CharField(blank=True, max_length=30)),
                ('target_type', models.CharField(blank=True, max_length=20)),
                ('has_performance_data', models.CharField(blank=True, max_length=20)),
                ('uploaded_data', models.TextField(blank=True)),
                ('jd_content', models.TextField(blank=True)),
                ('diagnostic_answers', models.TextField(blank=True)),
                ('selected_scenario', models.CharField(blank=True, max_length=5)),
                ('num_sessions', models.IntegerField(default=0)),
                ('final_plan', models.TextField(blank=True)),
                ('chat_history', models.TextField(blank=True, default='[]')),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('booked_date', models.CharField(blank=True, max_length=50)),
                ('booked_time', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('session_titles', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrimarySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=300)),
                ('primary_skills_text', models.TextField(blank=True)),
                ('sub_skills_text', models.TextField(blank=True)),
                ('role_applicability', models.CharField(default='Mgr, NM, IC', max_length=200)),
                ('is_manager_only', models.BooleanField(default=False)),
                ('program_tag', models.CharField(blank=True, max_length=100)),
                ('trainer_tag', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('foundational_outcomes', models.TextField(blank=True)),
                ('intermediate_outcomes', models.TextField(blank=True)),
                ('advanced_outcomes', models.TextField(blank=True)),
                ('expert_outcomes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['session_number'],
            },
        ),
        migrations.CreateModel(
            name='SubSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('definition', models.TextField(blank=True)),
                ('primary_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_skills', to='builder.primaryskill')),
            ],
        ),
    ]
