# Generated by Django 5.2.14 on 2026-05-21 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='builderrun',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='builderrun',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='builderrun',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builder_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='builderrun',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
