# Generated by Django 5.2.14 on 2026-05-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_add_user_and_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='builderrun',
            name='user_flags',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
