# Generated by Django 5.2.14 on 2026-05-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_builderrun_user_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='builderrun',
            name='observed_challenges',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='builderrun',
            name='role_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='builderrun',
            name='seniority_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='builderrun',
            name='success_metrics',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='builderrun',
            name='training_constraints',
            field=models.TextField(blank=True),
        ),
    ]
