# Generated by Django 5.2.14 on 2026-05-25 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_builderrun_ai_analysis_json_final_plan_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('context_collector', 'Context Collector — Stage 1 & 2 (question flow)'), ('analyzer', 'Analyzer — Stage 3 & 4 (recommendation)'), ('plan_generator', 'Plan Generator — Stage 5 (full training plan)'), ('general', 'General — Stage 6 & fallback')], max_length=50, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('model_name', models.CharField(default='gpt-4o', help_text='OpenAI model for this agent (e.g. gpt-4o, gpt-4o-mini)', max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=8000)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent Config',
                'verbose_name_plural': 'Agent Configs',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='PromptSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('identity', 'AI Identity & Role'), ('critical_rules', 'Critical Rules — Never Violate'), ('brand_tone', 'Brand Tone'), ('data_saving', 'Data Saving Instructions'), ('suggestions_rules', 'Suggestions — Rules & Format'), ('stage_1_flow', 'Stage 1 — Context Collection Flow (Q1-Q14)'), ('stage_2_paths', 'Stage 2 — Data Input Paths (A / B / C)'), ('confidence_logic', 'Confidence Score Logic'), ('stage_4_format', 'Stage 4 — Recommendation Format'), ('length_depth_rules', 'Length & Depth Rules'), ('stage_5_format', 'Stage 5 — Training Plan Format'), ('stage_5_rules', 'Stage 5 — Critical Rules'), ('tool_instructions', 'Tool Call Instructions'), ('stage_6_booking', 'Stage 6 — Booking Flow')], max_length=60, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('description', models.TextField(blank=True, help_text='What this section controls and what to be careful about when editing.')),
                ('order', models.PositiveSmallIntegerField(default=10, help_text='Assembly order — lower numbers appear earlier in the assembled prompt.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, help_text='Which agent uses this section. Leave blank = shared (all agents).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='builder.agentconfig')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_section_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt Section',
                'verbose_name_plural': 'Prompt Sections',
                'ordering': ['order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='PromptSectionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='builder.promptsection')),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
    ]
